server:
  port: 8080
spring:
  application:
    name: phone_system
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/phone_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 1234
  #redis
  redis:
    host: localhost
    port: 6379
    #password: 1234
    database: 0 #0????
    jedis:
      #Redis?????
      pool:
        max-active: 8
        max-wait: 1ms
        max-idle: 4
        min-idle: 0
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #如address_book---->AddressBook
    map-underscore-to-camel-case: true
    #开启mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #设置主键生成策略
      id-type: ASSIGN_ID

phoneSystem:
  path: D:/id
